project:
  type: website

website:
  title: "biostat777_intro_camryn_cohen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example_analysis.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



